- name: Install Java on Debian-based systems
  apt:
    name: "openjdk-11-jre-headless"
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Java on RedHat-based systems
  yum:
    name: "java-11-openjdk"
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

